[variables]
NIXPACKS_PHP_VERSION = '8.3'

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-scripts", "npm install"]

[phases.build]
cmds = ["php artisan package:discover --ansi", "npm run production"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT server.php"
