[phases.caddy]
dependsOn = ["setup"]
nixPkgs = ["caddy"]

[start]
cmd = "chmod -R 775 storage bootstrap/cache && php artisan migrate --force && { php-fpm -y /assets/php-fpm.conf & sleep 2; caddy run --config /app/Caddyfile 2>&1; }"
