[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_18", "npm-8_x"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs", "npm install"]

[phases.build]
cmds = ["npm run production"]

[start]
cmd = "php artisan migrate --force && php -S 0.0.0.0:$PORT server.php"

