[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PHP_VERSION = "8.2"

APP_KEY = "base64:7vF6Vf0V5L7X4F0T5L7X4F0T5L7X4F0T5L7X4F0T5L8="
PORT = "8080"

APP_NAME = "AskDocPH"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://askdocph-production-4dca.up.railway.app"
ASSET_URL = "https://askdocph-production-4dca.up.railway.app"
DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "nwCxwkveAQINZwyxnVmuGxULymvBvCqD"
CACHE_DRIVER = "file"
FILESYSTEM_DRIVER = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
BROADCAST_DRIVER = "log"
